// <auto-generated />
using System;
using DormCare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DormCare.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DormCare.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "New",
                            StudentId = 1,
                            Text = "Leaky faucet in room",
                            Type = "Maintenance"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 23, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Done",
                            StudentId = 2,
                            Text = "Request for extra blanket",
                            Type = "Service"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "New",
                            StudentId = 3,
                            Text = "Broken window latch",
                            Type = "Maintenance"
                        });
                });

            modelBuilder.Entity("DormCare.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            Number = "101A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 3,
                            Number = "102B"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 2,
                            Number = "103C"
                        });
                });

            modelBuilder.Entity("DormCare.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            RoomId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            RoomId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            RoomId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            RoomId = 3,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("DormCare.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@dorm.local",
                            FullName = "Administrator",
                            Password = "admin123",
                            Phone = "+380000000000",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ivanov@student.local",
                            FullName = "Ivan Ivanov",
                            Password = "password1",
                            Phone = "+380501111111",
                            Role = "Student",
                            Username = "ivanov"
                        },
                        new
                        {
                            Id = 3,
                            Email = "petrenko@student.local",
                            FullName = "Olena Petrenko",
                            Password = "password2",
                            Phone = "+380502222222",
                            Role = "Student",
                            Username = "petrenko"
                        },
                        new
                        {
                            Id = 4,
                            Email = "shevchenko@student.local",
                            FullName = "Taras Shevchenko",
                            Password = "password3",
                            Phone = "+380503333333",
                            Role = "Student",
                            Username = "shevchenko"
                        },
                        new
                        {
                            Id = 5,
                            Email = "koval@student.local",
                            FullName = "Anna Koval",
                            Password = "password4",
                            Phone = "+380504444444",
                            Role = "Student",
                            Username = "koval"
                        },
                        new
                        {
                            Id = 6,
                            Email = "melnyk@student.local",
                            FullName = "Oksana Melnyk",
                            Password = "password5",
                            Phone = "+380505555555",
                            Role = "Student",
                            Username = "melnyk"
                        });
                });

            modelBuilder.Entity("DormCare.Models.Request", b =>
                {
                    b.HasOne("DormCare.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormCare.Models.Student", b =>
                {
                    b.HasOne("DormCare.Models.Room", "Room")
                        .WithMany("Students")
                        .HasForeignKey("RoomId");

                    b.HasOne("DormCare.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DormCare.Models.Room", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
